export type MenuTag = "Recomendado" | "Sin TACC" | "Vegetariano";
export type MenuCategoryAccent = "entradas" | "principales" | "bebidas" | "ninos" | "postres";
export type MenuSectionId = "principales" | "pastas" | "pizzas" | "ensaladas" | "vinos" | "sin-alcohol" | "cafeteria" | "cervezas" | "aperitivos" | "gin-vermu" | "whisky";

export interface MenuOption { id: string; name: string; price?: string; }
export interface MenuOptionGroup { id: string; title: string; description: string; required?: boolean; options: MenuOption[]; }

export interface MenuItem {
  id: string;
  name: string;
  description?: string;
  price: string;
  image?: string;
  ingredients?: string[];
  pairing?: string;
  tags?: MenuTag[];
  section?: MenuSectionId;
  optionGroups?: MenuOptionGroup[];
  heading?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  description: string;
  shortDescription: string;
  accent: MenuCategoryAccent;
  items: MenuItem[];
  sections?: { id: MenuSectionId; name: string; emoji: string }[];
}

const garnishGroup: MenuOptionGroup = {
  id: "guarnicion", title: "Guarniciones disponibles", description: "Precios de la carta", options: [
    { id: "fritas", name: "Papas fritas", price: "$7.500" },
    { id: "fritas-huevo", name: "Papas fritas con huevo revuelto", price: "$8.000" },
    { id: "espanolas", name: "Papas españolas a la crema y verdeo", price: "$8.500" },
    { id: "pure-cabutia", name: "Puré de cabutia ahumada", price: "$7.000" },
    { id: "mixta", name: "Ensalada mixta", price: "$7.500" },
    { id: "estacion", name: "Ensalada de estación", price: "$7.500" },
    { id: "vegetales", name: "Vegetales grillados", price: "$8.500" },
  ],
};

const sauceGroup: MenuOptionGroup = {
  id: "salsa", title: "Salsas disponibles", description: "Opciones para acompañar la pasta", options: [
    { id: "bechamel", name: "Salsa bechamel" }, { id: "filetto", name: "Salsa filetto" },
    { id: "mixta", name: "Salsa mixta" }, { id: "bolognesa", name: "Salsa bolognesa" },
    { id: "blanca-puerro", name: "Salsa blanca con puerro" },
  ],
};

const extraSauceGroup: MenuOptionGroup = {
  id: "salsa-adicional", title: "Salsas adicionales", description: "Precios adicionales", options: [
    { id: "crema", name: "Crema de leche", price: "+$8.000" },
    { id: "panceta-verdeo", name: "Salsa blanca con panceta y verdeo", price: "+$8.000" },
    { id: "cuatro-quesos", name: "Salsa blanca con cuatro quesos", price: "+$8.000" },
    { id: "hongos", name: "Salsa blanca con hongos", price: "+$8.000" },
    { id: "mariscos", name: "Salsa de mariscos", price: "+$18.000" },
    { id: "langostinos", name: "Salsa de langostinos", price: "+$16.000" },
  ],
};

export const menuCategories: MenuCategory[] = [
  {
    id: "entradas",
    name: "Entradas",
    description: "Sabores de la casa para abrir la mesa y compartir.",
    shortDescription: "Para abrir la mesa.",
    accent: "entradas",
    items: [
      { id: "empanada-cordero", name: "Empanada de cordero", description: "Cordero, panceta, cebolla, verdeo, ají molido, sal y pimienta blanca.", price: "$4.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Empanada_%28versi%C3%B3n_argentina%29_de_carne_dulce.jpg/960px-Empanada_%28versi%C3%B3n_argentina%29_de_carne_dulce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Cordero", "Panceta", "Cebolla", "Verdeo", "Ají molido"], pairing: "Ideal para abrir la mesa." },
      { id: "empanada-carne", name: "Empanada de carne", description: "Matambre, cebolla, verdeo, pimentón, sal y pimienta blanca.", price: "$4.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Empanadas_de_carne_argentina_al_horno.jpg/960px-Empanadas_de_carne_argentina_al_horno.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Matambre", "Cebolla", "Verdeo", "Pimentón"], pairing: "Ideal para abrir la mesa." },
      { id: "empanada-cerdo", name: "Empanada de matambre de cerdo", description: "Matambre de cerdo, cebolla, verdeo, panceta, ají molido, sal y pimienta blanca.", price: "$4.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Empanada_%28versi%C3%B3n_argentina%29_de_carne_dulce.jpg/960px-Empanada_%28versi%C3%B3n_argentina%29_de_carne_dulce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Matambre de cerdo", "Cebolla", "Verdeo", "Panceta", "Ají molido"], pairing: "Ideal para abrir la mesa." },
      { id: "empanada-jamon-queso", name: "Empanada de jamón y quesos", description: "Jamón cocido, queso tybo, queso sardo y mozzarella.", price: "$3.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Fried_Argentine_empanadas_-_Beef%2C_corn%2C_ham_and_cheese.jpg/960px-Fried_Argentine_empanadas_-_Beef%2C_corn%2C_ham_and_cheese.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Jamón cocido", "Queso tybo", "Queso sardo", "Mozzarella"], pairing: "Ideal para abrir la mesa." },
      { id: "empanada-berenjena", name: "Empanada de berenjena y mozzarella", description: "Berenjena, cebolla, pimiento rojo, mozzarella, ají molido, sal y pimienta blanca.", price: "$3.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Empanada_al_horno_de_verduras.jpg/960px-Empanada_al_horno_de_verduras.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Berenjena", "Cebolla", "Pimiento rojo", "Mozzarella", "Ají molido"], pairing: "Ideal para abrir la mesa.", tags: ["Vegetariano"] },
      { id: "empanada-espinaca", name: "Empanada de espinaca y parmesano", description: "Espinaca, cebolla, mozzarella, queso sardo, nuez moscada, sal y pimienta blanca.", price: "$3.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Spinach_Empanadas_with_Poblano_Sauce_%283879653075%29.jpg/960px-Spinach_Empanadas_with_Poblano_Sauce_%283879653075%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Espinaca", "Cebolla", "Mozzarella", "Queso sardo", "Nuez moscada"], pairing: "Ideal para abrir la mesa.", tags: ["Vegetariano"] },
      { id: "empanada-calabaza", name: "Empanada de calabaza, queso y castañas", description: "Calabaza, cebolla, pimiento rojo, mozzarella, castaña de cajú y nuez moscada.", price: "$3.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Empanadas_de_flor_de_calabaza.jpg/960px-Empanadas_de_flor_de_calabaza.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Calabaza", "Cebolla", "Pimiento rojo", "Mozzarella", "Castaña de cajú"], pairing: "Ideal para abrir la mesa.", tags: ["Vegetariano"] },
      { id: "tortilla", name: "Tortilla de papas", description: "Papa, chorizo colorado, huevo, cebolla y alioli.", price: "$13.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tortilla_Espa%C3%B1ola_%28Spanish_Potato_Omelet%29.jpg/960px-Tortilla_Espa%C3%B1ola_%28Spanish_Potato_Omelet%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Papa", "Chorizo colorado", "Huevo", "Cebolla", "Alioli"], pairing: "Va muy bien con una cerveza roja.", tags: ["Sin TACC"] },
      { id: "tagliere-mar", name: "Tagliere di mare · Tabla de mar", description: "Rabas, mejillones, vieyras y langostinos rebozados, fritos y con aderezos. Para compartir.", price: "$47.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Fried_seafood_platter_in_Italy.jpg/960px-Fried_seafood_platter_in_Italy.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Rabas", "Mejillones", "Vieyras", "Langostinos", "Aderezos"], pairing: "Ideal con un vino blanco fresco.", tags: ["Recomendado"] },
      { id: "calamar-frito", name: "Calamar frito con aderezo picante", description: "Anillos de calamar rebozados y fritos.", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Fried_Calamari_Rings.jpg/960px-Fried_Calamari_Rings.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Calamar", "Rebozado", "Aderezo picante"], pairing: "Acompañalo con una cerveza o vino blanco." },
      { id: "bunuelo", name: "Buñuelos de espinaca y queso sardo", description: "Con aderezo de remolacha.", price: "$12.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Actual_spinach_fritters.jpg/960px-Actual_spinach_fritters.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Espinaca", "Cebolla", "Huevo", "Queso sardo", "Remolacha"], pairing: "Acompañalos con un aperitivo cítrico.", tags: ["Vegetariano"] },
      { id: "panini-alma", name: "Panini del Alma", description: "Masa madre, burrata, mortadela, rúcula, queso sardo y tomates cherry.", price: "$19.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Panini_sandwich_near_Mirpur_10_%282%29.jpg/960px-Panini_sandwich_near_Mirpur_10_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Masa madre", "Burrata", "Mortadela", "Rúcula", "Queso sardo", "Tomates cherry"], pairing: "Ideal con una copa de blanco fresco." },
      { id: "panini-pueblo", name: "Panini del Pueblo", description: "Masa madre, burrata, jamón crudo, rúcula, tomates cherry y queso sardo.", price: "$19.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/AK_Meats_1_2_Ham_Hoagie_%2830137391191%29.jpg/960px-AK_Meats_1_2_Ham_Hoagie_%2830137391191%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Masa madre", "Burrata", "Jamón crudo", "Rúcula", "Tomates cherry", "Queso sardo"], pairing: "Ideal con una copa de blanco fresco." },
    ],
  },
  {
    id: "principales",
    name: "Principales",
    description: "Carnes, pesca y pastas con el carácter de nuestra cocina.",
    shortDescription: "Carnes, pesca y pastas.",
    accent: "principales",
    sections: [
      { id: "principales", name: "Principales", emoji: "🍽️" },
      { id: "pastas", name: "Pastas", emoji: "🍝" },
      { id: "pizzas", name: "Pizzas", emoji: "🍕" },
      { id: "ensaladas", name: "Ensaladas", emoji: "🥗" },
    ],
    items: [
      { id: "ojo-bife", section: "principales", name: "Ojo de bife con hueso", price: "$34.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Ribeye_steak%2C_hot_off_the_grill.jpg/960px-Ribeye_steak%2C_hot_off_the_grill.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [garnishGroup], tags: ["Sin TACC"] },
      { id: "bife-chorizo", section: "principales", name: "Bife de chorizo", price: "$34.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Grilled_Sirloin_Steak_with_Vegetables.jpg/960px-Grilled_Sirloin_Steak_with_Vegetables.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [garnishGroup], tags: ["Sin TACC"] },
      { id: "salmon", section: "principales", name: "Salmón rosado", price: "$37.000", image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Grilled_plated_salmon_fillet_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", optionGroups: [garnishGroup], tags: ["Sin TACC"] },
      { id: "molleja-verdeo", section: "principales", name: "Molleja al verdeo", description: "Con puré de papas.", price: "$27.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Fried_and_glazed_veal_sweetbread%2C_grilled_cabbage%2C_dill_and_white_currants%2C_verbana%2C_fermented_garlic_%2826633260503%29.jpg/960px-Fried_and_glazed_veal_sweetbread%2C_grilled_cabbage%2C_dill_and_white_currants%2C_verbana%2C_fermented_garlic_%2826633260503%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Molleja", "Verdeo", "Puré de papas"], optionGroups: [garnishGroup], tags: ["Sin TACC"] },
      { id: "osobuco-milanese", section: "principales", name: "Osobuco alla milanese", description: "Con risotto alla spinaci.", price: "$30.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Ossobuco_con_risotto_alla_milanese.jpg/960px-Ossobuco_con_risotto_alla_milanese.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Osobuco", "Risotto", "Espinaca"], optionGroups: [garnishGroup] },
      { id: "pacu", section: "principales", name: "Pacú · Pesca del día", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Plated_grilled_fish_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", optionGroups: [garnishGroup], tags: ["Sin TACC"] },
      { id: "milanesa-alma", section: "principales", name: "Milanesa del Alma", description: "Papas fritas, huevo frito y ketchup.", price: "$35.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Milanesa.jpg/960px-Milanesa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Recomendado"], optionGroups: [garnishGroup] },
      { id: "milanesa-bomba", section: "principales", name: "Milanesa del Alma Bomba", description: "Papas fritas, salsa de tomate, jamón cocido, queso tybo, cebolla caramelizada, queso sardo, huevos fritos, panceta ahumada y ketchup.", price: "$42.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Milanesa_napolitana_argentina.jpg/960px-Milanesa_napolitana_argentina.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [garnishGroup] },
      { id: "risotto-gamberi", section: "principales", name: "Risotto ai gamberi", description: "Langostinos, arroz carnaroli y tinta de calamar.", price: "$27.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Shrimp_risotto_at_Sea_Me_%2822180902028%29.jpg/960px-Shrimp_risotto_at_Sea_Me_%2822180902028%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Sin TACC"] },
      { id: "risotto-calabaza", section: "principales", name: "Risotto de calabaza asada", description: "Queso azul y nueces tostadas.", price: "$21.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Chicken_and_Pumpkin_Risotto-_Air%2C_David_Jones%2C_Chadstone_%281238453950%29.jpg/960px-Chicken_and_Pumpkin_Risotto-_Air%2C_David_Jones%2C_Chadstone_%281238453950%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano", "Sin TACC"] },
      { id: "milanese-vitello", section: "principales", name: "Milanese di vitello", description: "Con caserecce en rueda de reggianito estacionado. Opcional a caballo: $2.000.", price: "$42.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Milanesa.jpg/960px-Milanesa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "caserecce-ruota", section: "pastas", heading: "Pasta corta a la rueda", name: "Caserecce cacio e pepe alla ruota", description: "Pasta finalizada en rueda de reggianito, con champiñones, panceta y verdeo.", price: "$29.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Gnocchetti_Pasta_from_Truffle_Parmesean_Wheel_from_Grissini.jpg/960px-Gnocchetti_Pasta_from_Truffle_Parmesean_Wheel_from_Grissini.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Recomendado"] },
      { id: "tagliatelle-carbonara", section: "pastas", heading: "Pastas", name: "Tagliatelle carbonara", description: "Molleja, panceta, verdeo y salsa cremosa de yemas y queso sardo.", price: "$30.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/MOs810%2C_WG_51_2024_ZachLub_tagliatelle_carbonara_%C5%9Awidnik.jpg/960px-MOs810%2C_WG_51_2024_ZachLub_tagliatelle_carbonara_%C5%9Awidnik.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "tagliatelle-langostinos", section: "pastas", name: "Tagliatelle con tomates y langostinos", description: "Queso sardo, langostinos y tomate concasé.", price: "$30.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Shrimp_pasta.jpg/960px-Shrimp_pasta.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "noquis-ricota", section: "pastas", name: "Cazuela de ñoquis de ricota y espinaca", price: "$19.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Buffalo_Ricotta_Gnocchi_with_toasted_Agassiz_hazelnuts%2C_blue_cheese%2C_white_wine_and_North_Arm_Farm_spinach_%285895883294%29.jpg/960px-Buffalo_Ricotta_Gnocchi_with_toasted_Agassiz_hazelnuts%2C_blue_cheese%2C_white_wine_and_North_Arm_Farm_spinach_%285895883294%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup], tags: ["Vegetariano"] },
      { id: "noquis-papa", section: "pastas", name: "Cazuela de ñoquis de papa", price: "$16.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Gnocchi_di_patate_con_sugo_di_pomodoro_e_con_gorgonzola.jpg/960px-Gnocchi_di_patate_con_sugo_di_pomodoro_e_con_gorgonzola.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup], tags: ["Vegetariano"] },
      { id: "lasagna-ternera", section: "pastas", heading: "Pasta rellena", name: "Lasagna de ternera", description: "Ternera braseada, champiñones, cebolla, pimiento y mozzarella.", price: "$27.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Meaty_Lasagna_8of8_%288736299782%29.jpg/960px-Meaty_Lasagna_8of8_%288736299782%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "canelones-ternera", section: "pastas", name: "Canelones de ternera braseada", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Cannelloni2.png/960px-Cannelloni2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "ravioles-salmon", section: "pastas", name: "Ravioles de salmón", description: "Salmón rosado, queso brie, pimiento, ciboulette, tomate y cebolla.", price: "$27.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Salmon_and_ravioli_at_home.jpg/960px-Salmon_and_ravioli_at_home.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "sorrentinos-ternera", section: "pastas", name: "Sorrentinos de ternera", description: "Ternera ahumada, hongos, cebolla y queso tybo.", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Ravioles_argentinos_de_jam%C3%B3n_y_queso.jpg/960px-Ravioles_argentinos_de_jam%C3%B3n_y_queso.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "sorrentinos-hongos", section: "pastas", name: "Sorrentinos de hongo de pino", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ravioli_with_forest_mushrooms%2C_Limburg.jpg/960px-Ravioli_with_forest_mushrooms%2C_Limburg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup], tags: ["Vegetariano"] },
      { id: "sorrentinos-jamon", section: "pastas", name: "Sorrentinos de jamón y queso", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Ravioles_argentinos_de_jam%C3%B3n_y_queso.jpg/960px-Ravioles_argentinos_de_jam%C3%B3n_y_queso.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "sorrentinos-calabaza", section: "pastas", name: "Sorrentinos de calabaza", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Pumpkin_Ravioli_with_Chestnuts_and_Goats_Curd%2C_looks_incredible%21_A_treat_to_salvage_my_day_from_Naked_for_Satan._%2832970349656%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", optionGroups: [sauceGroup, extraSauceGroup], tags: ["Vegetariano"] },
      { id: "panzottis-mar", section: "pastas", name: "Panzottis de mar", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lobster_Ravioli_from_Quattro_in_Little_Italy_In_Boston%2C_MA.jpg/960px-Lobster_Ravioli_from_Quattro_in_Little_Italy_In_Boston%2C_MA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "panzottis-cordero", section: "pastas", name: "Panzottis de cordero", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Lamb_ravioli.jpg/960px-Lamb_ravioli.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "ravioles-osobuco", section: "pastas", name: "Ravioles de osobuco", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/8/86/Ravioli_di_Faraona.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", optionGroups: [sauceGroup, extraSauceGroup] },
      { id: "ravioles-espinaca", section: "pastas", name: "Ravioles de espinaca", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Liat_Portal_for_Foodie_Disorder_-_Ravioli_with_mushrooms_and_spinach_in_cream_sauce.jpg/960px-Liat_Portal_for_Foodie_Disorder_-_Ravioli_with_mushrooms_and_spinach_in_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", optionGroups: [sauceGroup, extraSauceGroup], tags: ["Vegetariano"] },

      { id: "pizza-clasica", section: "pizzas", name: "Clásica", description: "Mozzarella, salsa de tomate, orégano y olivas verdes.", price: "$18.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Margherita_Originale.JPG/960px-Margherita_Originale.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-napolitana", section: "pizzas", name: "Napolitana", description: "Mozzarella, tomate, aceite de ajo y olivas verdes.", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Pizza_Tradici%C3%B3n_Napolitana.jpg/960px-Pizza_Tradici%C3%B3n_Napolitana.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-burrata", section: "pizzas", name: "Burrata", description: "Mozzarella, salsa de tomate, burrata, pesto, albahaca y olivas verdes.", price: "$27.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Pizza_burrata.jpg/960px-Pizza_burrata.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Recomendado", "Vegetariano"] },
      { id: "pizza-fugazzeta", section: "pizzas", name: "Fugazzeta", description: "Mozzarella, cebolla, queso sardo y olivas negras.", price: "$19.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Pizza_Berlusconi_in_Lauttasaari.jpg/960px-Pizza_Berlusconi_in_Lauttasaari.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-especial", section: "pizzas", name: "Especial", description: "Jamón cocido, queso sardo, morrones y olivas verdes.", price: "$22.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pizza_with_ham_and_banana_peppers.jpg/960px-Pizza_with_ham_and_banana_peppers.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "pizza-hawaii", section: "pizzas", name: "Hawaii", description: "Mozzarella, ananá, jamón cocido, azúcar mascabo y olivas negras.", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Hawaiian_pizza_1.jpg/960px-Hawaiian_pizza_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "pizza-peras", section: "pizzas", name: "Peras", description: "Mozzarella, peras, queso azul, tomillo y nueces.", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Walnut_pear_pizza.jpg/960px-Walnut_pear_pizza.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-verdeo", section: "pizzas", name: "Verdeo y panceta", price: "$24.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Pizza_Cipolla_..._%28Bacon%2C_Thyme%2C_Red_Onions%2C_Avo%2C_Crispy_Onions%29.jpg/960px-Pizza_Cipolla_..._%28Bacon%2C_Thyme%2C_Red_Onions%2C_Avo%2C_Crispy_Onions%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "pizza-cuatro-quesos", section: "pizzas", name: "Cuatro quesos", price: "$24.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg/960px-Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-rucula", section: "pizzas", name: "Rúcula y jamón crudo", price: "$24.000", image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Prosciutto_Rucola_-_tomato%2C_mozzarella%2C_arugula%2C_prosciutto_di_Parma%2C_pecorino_%2816103892980%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "pizza-funghi", section: "pizzas", name: "Funghi", price: "$21.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Pepperoni_and_mushroom_pizza_-_Massachusetts.jpg/960px-Pepperoni_and_mushroom_pizza_-_Massachusetts.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Vegetariano"] },
      { id: "pizza-langostinos", section: "pizzas", name: "De langostinos", price: "$24.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Shrimp_pizza_from_Panago.jpg/960px-Shrimp_pizza_from_Panago.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "ensalada-burrata", section: "ensaladas", name: "Ensalada de burrata", description: "Rúcula, burrata, pesto de perejil y menta, picles de cebolla, chutney de mango y nuez.", price: "$28.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Burrata_salad_with_arugula%2C_fig_jam%2C_and_pistachios_-_San_Francisco%2C_CA.jpg/960px-Burrata_salad_with_arugula%2C_fig_jam%2C_and_pistachios_-_San_Francisco%2C_CA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Sin TACC", "Vegetariano"] },
      { id: "ensalada-caesar", section: "ensaladas", name: "Ensalada Caesar", description: "Pollo, lechuga, queso sardo, croutons, panceta, huevo poché y aderezo Caesar.", price: "$18.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Caesar_salad_%282%29.jpg/960px-Caesar_salad_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "ensalada-calabaza", section: "ensaladas", name: "Ensalada de calabaza y queso roquefort", description: "Mix de verdes, cebolla caramelizada, naranja, queso azul, nueces y sésamo.", price: "$22.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Boiled_pumpkin_with_roasted_sweet_potato_and_vegetables.jpg/960px-Boiled_pumpkin_with_roasted_sweet_potato_and_vegetables.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Sin TACC", "Vegetariano"] },
    ],
  },
  {
    id: "bebidas",
    name: "Bodega y bebidas",
    description: "Nuestra selección de vinos, bebidas, cafetería y coctelería.",
    shortDescription: "Bodega, bebidas y coctelería.",
    accent: "bebidas",
    sections: [
      { id: "vinos", name: "Vinos", emoji: "🍷" },
      { id: "sin-alcohol", name: "Sin alcohol", emoji: "🥤" },
      { id: "cafeteria", name: "Cafetería", emoji: "☕" },
      { id: "cervezas", name: "Cervezas", emoji: "🍺" },
      { id: "aperitivos", name: "Aperitivos", emoji: "🍹" },
      { id: "gin-vermu", name: "Gin y Vermú", emoji: "🍸" },
      { id: "whisky", name: "Whisky", emoji: "🥃" },
    ],
    items: [
      { id: "sangria-verano", section: "vinos", heading: "Sangría y tinto de verano", name: "Sangría · Tinto de verano", description: "Emilia Malbec o Benjamín Malbec.", price: "$12.500 botella · $4.500 copa", image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Red_Wine_Sangria_with_lemon%2C_lime%2C_apple%2C_and_orange_served_in_a_glass_-_Evan_Swigart.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", tags: ["Recomendado"] },
      { id: "cadus", section: "vinos", heading: "Tintos", name: "Cadus Appellation", description: "Malbec, Cabernet, Pinot Noir o Petit Verdot.", price: "$43.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wine_Tasting-_Malbec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "perdices-exploracion", section: "vinos", name: "Las Perdices Exploración Geográfica", description: "La Consulta, Paraje Altamira, Gualtallary o Chacayes Malbec.", price: "$39.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wine_Tasting-_Malbec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "ruca-dos", section: "vinos", name: "Ruca Malén Capítulo Dos", description: "Malbec, Petit Verdot o Cabernet.", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Andrew_Will_Champoux_Vineyard_Red_Wine_%282005%29.jpg/960px-Andrew_Will_Champoux_Vineyard_Red_Wine_%282005%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nicanor-cabernet", section: "vinos", name: "Don Nicanor Cabernet Sauvignon", price: "$30.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Stag%27s_Leap_Wine_Cellars_Cabernet_Sauvignon_CASK_23_1997.jpg/960px-Stag%27s_Leap_Wine_Cellars_Cabernet_Sauvignon_CASK_23_1997.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nicanor-malbec", section: "vinos", name: "Don Nicanor Malbec", price: "$30.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wine_Tasting-_Malbec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "lamadrid", section: "vinos", name: "Lamadrid Reserva", description: "Bonarda, Malbec, Cabernet Franc o Cabernet Sauvignon.", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Bodega_Reserva_Malbec_2006.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "salentein-tinto", section: "vinos", name: "Salentein Reserva", description: "Malbec, Cabernet, Merlot o Cabernet Franc.", price: "$26.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Andrew_Will_Champoux_Vineyard_Red_Wine_%282005%29.jpg/960px-Andrew_Will_Champoux_Vineyard_Red_Wine_%282005%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-cabernet", section: "vinos", name: "Nieto Senetiner Cabernet Sauvignon", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Paso_Robles_cab.jpg/960px-Paso_Robles_cab.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-malbec", section: "vinos", name: "Nieto Senetiner Malbec", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Argentinean_Malbec_in_stemless_wine_glass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "nieto-pinot", section: "vinos", name: "Nieto Senetiner Pinot Noir", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Pinot_Noir_being_poured_into_a_wine_glass.jpg/960px-Pinot_Noir_being_poured_into_a_wine_glass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nicanor-sangiovese", section: "vinos", name: "Don Nicanor Sangiovese", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Parkside_Wine_Bar_-_November_2023_-_Sarah_Stierch_01.jpg/960px-Parkside_Wine_Bar_-_November_2023_-_Sarah_Stierch_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "killka-corte", section: "vinos", name: "Killka Corte de Tintas", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Paso_Robles_red_blend_unique_wine_bottle.jpg/960px-Paso_Robles_red_blend_unique_wine_bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "ruca-uno", section: "vinos", name: "Ruca Malén Capítulo Uno Malbec", price: "$16.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wine_Tasting-_Malbec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "portillo-malbec", section: "vinos", name: "Portillo Malbec", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wine_Tasting-_Malbec.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "cocktail-sangria", section: "vinos", heading: "Emilia Nieto Senetiner Cocktails", name: "Emilia Cocktail · Sangría", description: "Malbec y Bonarda infusionados con naranja y botánicos.", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Sangria_in_a_tall_skinny_glass_in_Malaga.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "cocktail-clarea", section: "vinos", name: "Emilia Cocktail · Clarea", description: "Semillón y Chenin infusionados con limón y flor de sauco.", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/White_wine_spritzer.jpg/960px-White_wine_spritzer.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cocktail-rose", section: "vinos", name: "Emilia Cocktail · Rosé", description: "Syrah y Bonarda infusionados con pomelo e hibiscus.", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Self-made_gin_pink_grapefruit_long_drink.jpg/960px-Self-made_gin_pink_grapefruit_long_drink.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cocktail-spritz", section: "vinos", name: "Emilia Cocktail · Spritz", description: "Pinot Noir y Malbec infusionados con naranja y bitter.", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Blood_Orange_Spritz_-_Sarah_Stierch.jpg/960px-Blood_Orange_Spritz_-_Sarah_Stierch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nicanor-chardonnay", section: "vinos", heading: "Blancos", name: "Don Nicanor Chardonnay", price: "$28.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Wismer_-_Foxcroft_Vineyard_-_2017_Chardonnay_-_Wine_Label.jpg/960px-Wismer_-_Foxcroft_Vineyard_-_2017_Chardonnay_-_Wine_Label.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "lamadrid-chardonnay", section: "vinos", name: "Lamadrid Reserva Chardonnay", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Vina_Maipo_-_Chardonnay_Valle_Central_2010.JPG/960px-Vina_Maipo_-_Chardonnay_Valle_Central_2010.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-chardonnay", section: "vinos", name: "Nieto Senetiner Chardonnay", price: "$21.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Chardonnay_-_Passaggio_Wines_-_Stierch_-_October_2018.jpg/960px-Chardonnay_-_Passaggio_Wines_-_Stierch_-_October_2018.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "salentein-sauvignon", section: "vinos", name: "Salentein Reserva Sauvignon Blanc", price: "$26.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/J._Lohr_Sauvignon_blanc_glass_and_bottle.jpg/960px-J._Lohr_Sauvignon_blanc_glass_and_bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "perdices-torrontes", section: "vinos", name: "Las Perdices Torrontés", price: "$22.000", image: "https://upload.wikimedia.org/wikipedia/commons/7/71/White_Wine_Glas.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "killka-chardonnay", section: "vinos", name: "Killka Chardonnay", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Wismer_-_Foxcroft_Vineyard_-_2017_Chardonnay_-_Wine_Label.jpg/960px-Wismer_-_Foxcroft_Vineyard_-_2017_Chardonnay_-_Wine_Label.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "emilia-moscatel", section: "vinos", name: "Emilia Dulce Natural Moscatel", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Caligiari_Moscato.jpg/960px-Caligiari_Moscato.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "emilia-rosado", section: "vinos", heading: "Rosados", name: "Emilia Rosado", price: "$15.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Glass_of_ros%C3%A9_sparkling_wine_-_Sarah_Stierch.jpg/960px-Glass_of_ros%C3%A9_sparkling_wine_-_Sarah_Stierch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-rosado", section: "vinos", name: "Nieto Senetiner Rosado", price: "$20.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Rose_and_black_sparking_wine_at_home.jpg/960px-Rose_and_black_sparking_wine_at_home.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "copa-malbec", section: "vinos", heading: "Vino por copa", name: "Copa Las Perdices Partridge Malbec", price: "$6.000", image: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Argentinean_Malbec_in_stemless_wine_glass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "copa-chardonnay", section: "vinos", name: "Copa Las Perdices Reserva Chardonnay", price: "$6.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/A_hand_pours_white_wine_from_a_bottle_into_a_glass%2C_capturing_the_festive_spirit_of_a_gathering_in_a_garden.jpg/960px-A_hand_pours_white_wine_from_a_bottle_into_a_glass%2C_capturing_the_festive_spirit_of_a_gathering_in_a_garden.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "chandon", section: "vinos", heading: "Espumantes", name: "Chandon Reserva Pinot Cuvée", price: "$42.500", image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Sparkling_wine_in_riddling_rack.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "bousquet-rose", section: "vinos", name: "Bousquet Rosé", price: "$24.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Sparkling_and_rose_wine_with_wine_saver_capsules_on.jpg/960px-Sparkling_and_rose_wine_with_wine_saver_capsules_on.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-extra-brut", section: "vinos", name: "Nieto Senetiner Extra Brut", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Sparkling_wine_in_a_flute.jpg/960px-Sparkling_wine_in_a_flute.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "nieto-brut-nature", section: "vinos", name: "Nieto Senetiner Brut Nature", price: "$23.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Pouring_sparkling_wine_into_a_flute.jpg/960px-Pouring_sparkling_wine_into_a_flute.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "agua", section: "sin-alcohol", name: "Agua mineral con o sin gas", price: "$3.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Acqua_Panna_mineral_water_in_a_glass_bottle_-_20140408.jpg/960px-Acqua_Panna_mineral_water_in_a_glass_bottle_-_20140408.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "agua-saborizada", section: "sin-alcohol", name: "Agua saborizada", price: "$3.900", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Sparkling_Ice_Lemonade_Flavored_Water.jpg/960px-Sparkling_Ice_Lemonade_Flavored_Water.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "gaseosa-350", section: "sin-alcohol", name: "Gaseosa 350 cc", price: "$3.600", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chilled_glass_of_Coca-Cola_at_Siipiweikot_Kamppi.jpg/960px-Chilled_glass_of_Coca-Cola_at_Siipiweikot_Kamppi.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "gaseosa-500", section: "sin-alcohol", name: "Gaseosa 500 cc", price: "$3.900", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Coca-Cola_Bottle.jpg/960px-Coca-Cola_Bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "pomelada", section: "sin-alcohol", name: "Pomelada", description: "Pomelo, menta y azúcar o edulcorante.", price: "$9.500 jarra · $5.000 vaso", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ting_drink_%28grapefruit_flavour%29.jpg/960px-Ting_drink_%28grapefruit_flavour%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "limonada", section: "sin-alcohol", name: "Limonada", description: "Limón, jengibre, menta y azúcar o edulcorante.", price: "$9.500 jarra · $5.000 vaso", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Gerard_ter_Borch_%28II%29_-_The_Glass_of_Lemonade_-_WGA22118.jpg/960px-Gerard_ter_Borch_%28II%29_-_The_Glass_of_Lemonade_-_WGA22118.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "cafe", section: "cafeteria", name: "Café", price: "$2.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Espresso_Coffee_01.jpg/960px-Espresso_Coffee_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cafe-crema", section: "cafeteria", name: "Café con crema", price: "$3.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cup_of_Coffee_with_Whipped_Cream.jpg/960px-Cup_of_Coffee_with_Whipped_Cream.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cafe-leche", section: "cafeteria", name: "Café con leche", price: "$3.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Caf%C3%A9_con_leche_acompa%C3%B1ado_de_chipitas_misioneras%2C_facturas_de_confiter%C3%ADa%2C_almendras_y_semillas.jpg/960px-Caf%C3%A9_con_leche_acompa%C3%B1ado_de_chipitas_misioneras%2C_facturas_de_confiter%C3%ADa%2C_almendras_y_semillas.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cafe-doble", section: "cafeteria", name: "Café doble", price: "$3.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Double_espresso_%282259728230%29.jpg/960px-Double_espresso_%282259728230%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cafe-doble-crema", section: "cafeteria", name: "Café doble con crema", price: "$4.200", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Espresso_with_whipped_cream_%28Unsplash%29.jpg/960px-Espresso_with_whipped_cream_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "te", section: "cafeteria", name: "Té", price: "$1.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Cup_of_black_tea.JPG/960px-Cup_of_black_tea.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "te-saborizado", section: "cafeteria", name: "Té saborizado", price: "$1.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Hot_tea._8_minutes_fruit_infusion.jpg/960px-Hot_tea._8_minutes_fruit_infusion.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "heineken-litro", section: "cervezas", name: "Heineken 1000 cc", price: "$9.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Beer_bottles_2018_G1.jpg/960px-Beer_bottles_2018_G1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "warsteiner", section: "cervezas", name: "Warsteiner 1000 cc", price: "$6.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Paulaner_Oktoberfest_Marzen_11.2oz_bottle_and_beer_mug.jpg/960px-Paulaner_Oktoberfest_Marzen_11.2oz_bottle_and_beer_mug.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "imperial-litro", section: "cervezas", name: "Imperial IPA o Golden 1000 cc", price: "$8.000", image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Hoppy_Hog_Palianytsia_Ukrainian_Golden_Ale.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "imperial-330", section: "cervezas", name: "Imperial Golden 330 cc", price: "$2.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Imperial_Golden%2C_Extra_Lager%2C_IPA_bottles.jpg/960px-Imperial_Golden%2C_Extra_Lager%2C_IPA_bottles.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "heineken-330", section: "cervezas", name: "Heineken 330 cc", price: "$4.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Heineken_Bottle.jpg/960px-Heineken_Bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "miller-330", section: "cervezas", name: "Miller 330 cc", price: "$2.800", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Miller_Lite_%282639815996%29.jpg/960px-Miller_Lite_%282639815996%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "sin-alcohol-330", section: "cervezas", name: "Long neck sin alcohol 330 cc", price: "$3.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/038_Peroni_non-alcoholic_beer_-_bottled_low_alcohol_Italian_beer_brand.jpg/960px-038_Peroni_non-alcoholic_beer_-_bottled_low_alcohol_Italian_beer_brand.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "imperial-stout", section: "cervezas", name: "Imperial Stout 473 cc", price: "$3.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bottle%2C_beer_%28AM_604186%29.jpg/960px-Bottle%2C_beer_%28AM_604186%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "imperial-roja", section: "cervezas", name: "Imperial Roja 473 cc", price: "$3.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Independent_Connemara_Red_Ale_%2827422919395%29.jpg/960px-Independent_Connemara_Red_Ale_%2827422919395%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },

      { id: "gancia", section: "aperitivos", name: "Aperitivo Gancia", price: "Happy hour 2 × $3.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Chrysanthemum_cocktail.jpg/960px-Chrysanthemum_cocktail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "campari", section: "aperitivos", name: "Campari Orange", description: "Campari con jugo de naranja.", price: "$10.000 · HH 2 × $12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Campari_Orange.jpg/960px-Campari_Orange.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "negroni", section: "aperitivos", name: "Negroni", description: "Gin, rosso y Campari.", price: "$8.000 · HH 2 × $9.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Negroni_%28cocktail%29.jpg/960px-Negroni_%28cocktail%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cynar-julep", section: "aperitivos", name: "Cynar Julep", description: "Cynar, pomelo, limón, menta y almíbar.", price: "$10.000 · HH 2 × $12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mint_Julep_at_Rye%2C_San_Francisco.jpg/960px-Mint_Julep_at_Rye%2C_San_Francisco.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "aperol", section: "aperitivos", name: "Aperol Spritz", description: "Aperol, espumante, soda y naranja.", price: "$10.000 · HH 2 × $12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Aperol_Spritz_-_Santa_Ynez_Kitchen_-_Sarah_Stierch.jpg/960px-Aperol_Spritz_-_Santa_Ynez_Kitchen_-_Sarah_Stierch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "fernet", section: "aperitivos", name: "Fernet Branca medida", price: "$8.000 · HH 2 × $9.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Hanky_Panky_cocktail.jpg/960px-Hanky_Panky_cocktail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "mojito", section: "aperitivos", name: "Mojito", description: "Ron Havana añejo, limón, almíbar y menta.", price: "$10.000 · HH 2 × $12.000", image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Rum_Day_Mojito_instructions_shaker_sugar_lime_juice_mint_leaves_glass_ice_cubes_%2818675336852%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },

      { id: "gin-tonic", section: "gin-vermu", name: "Gin Tonic", description: "Príncipe de los Apóstoles, Pulpo Blanco tónica y cítrico a elección.", price: "$9.000 · HH 2 × $12.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Gin_and_Tonic_with_ingredients.jpg/960px-Gin_and_Tonic_with_ingredients.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "ap-ap-tonic", section: "gin-vermu", name: "AP AP Tonic", description: "Gin, tónica, Aperol, naranja y menta.", price: "$9.000 · HH 2 × $12.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Hartwall_Orange_Gin_Long_Drink.jpg/960px-Hartwall_Orange_Gin_Long_Drink.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cyn-tonic", section: "gin-vermu", name: "Cyn Tonic", description: "Gin, Cynar, tónica, pomelo y romero.", price: "$7.800 · HH 2 × $12.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Gin_and_tonic_at_the_Fairmont_Washington_DC_-_Sarah_Stierch.jpg/960px-Gin_and_tonic_at_the_Fairmont_Washington_DC_-_Sarah_Stierch.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "giovannoni", section: "gin-vermu", name: "Giovannoni Rosso o Seco", description: "Tónica, soda y rodaja de cítricos.", price: "$5.000 · HH 2 × $7.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Four_bottles_of_vermouth.jpg/960px-Four_bottles_of_vermouth.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "cinzano", section: "gin-vermu", name: "Cinzano Rosso o Bianco", price: "$5.000 · HH 2 × $7.500", image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Vermouth.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },

      { id: "johnnie-negro", section: "whisky", name: "Johnnie Walker Black", price: "$9.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Johnnie_Walker_Black_Label.jpg/960px-Johnnie_Walker_Black_Label.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "johnnie-rojo", section: "whisky", name: "Johnnie Walker Red", price: "$6.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Johnnie_Walker_Red_Label.jpg/960px-Johnnie_Walker_Red_Label.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "jb", section: "whisky", name: "J&B", price: "$5.500", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Macallan_Amber_Scotch_whisky.jpg/960px-Macallan_Amber_Scotch_whisky.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
    ],
  },
  {
    id: "ninos",
    name: "Menú bambino",
    description: "Sabores simples y porciones pensadas para los más chicos.",
    shortDescription: "Para los más chicos.",
    accent: "ninos",
    items: [
      { id: "milanesa-bambino", name: "Milanesa bambino", description: "Con papas fritas o puré, huevo frito y ketchup.", price: "$25.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Cutlet_in_Poznan_City_Park.jpg/960px-Cutlet_in_Poznan_City_Park.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Ternera", "Papas o puré", "Huevo", "Ketchup"], pairing: "Ideal con agua o limonada." },
      { id: "tagliatelle-bambino", name: "Tagliatelle bambino", description: "Pasta casera con salsa roja, blanca, mixta o aceite de oliva.", price: "$16.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Primer_plano_de_tallarines_argentinos_a_la_manteca_con_queso_rallado.jpg/960px-Primer_plano_de_tallarines_argentinos_a_la_manteca_con_queso_rallado.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", ingredients: ["Tagliatelle casero", "Salsa a elección"], pairing: "Una opción simple para los más chicos.", tags: ["Vegetariano"] },
    ],
  },
  {
    id: "postres",
    name: "Postres",
    description: "El mejor cierre para una gran comida.",
    shortDescription: "Dulces de cierre.",
    accent: "postres",
    items: [
      { id: "volcan-dulce-leche", name: "Volcán de dulce de leche", description: "Con helado de crema Cremolatti. 15 minutos de cocción.", price: "$12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Chocolate_lava_cake.jpg/960px-Chocolate_lava_cake.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "volcan-chocolate", name: "Volcán de chocolate", description: "Con helado de crema Cremolatti. 15 minutos de cocción.", price: "$12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Chocolate_lava_cake.jpg/960px-Chocolate_lava_cake.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "tiramisu", name: "Tiramisú clásico", description: "Capas de vainilla mojadas en café y una lluvia de cacao amargo.", price: "$12.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/A_slice_of_tiramisu_cake.jpg/960px-A_slice_of_tiramisu_cake.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "affogato", name: "Affogato del Alma", description: "Helado de crema Cremolatti, galleta de almendra, café Segafredo y Amarula.", price: "$10.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Affogato.JPG/960px-Affogato.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
      { id: "merengata", name: "Merengata del Pueblo", description: "Pionono de vainilla, helado de crema Cremolatti, merengue italiano quemado y espejo de chocolate.", price: "$10.000", image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Baked-Alaska.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
      { id: "creme-brulee", name: "Crème brûlée", description: "Crema suave de vainilla con una capa de azúcar caramelizada.", price: "$10.000", image: "https://upload.wikimedia.org/wikipedia/commons/9/91/Cr%C3%A8me_br%C3%BBl%C3%A9e_w._whipped_cream.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", tags: ["Sin TACC"] },
      { id: "flan", name: "Flan casero", description: "Con crema, dulce de leche o mixto.", price: "$8.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Homemade_Flan.jpg/960px-Homemade_Flan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", tags: ["Sin TACC"] },
      { id: "panqueques", name: "Panqueques con dulce de leche", description: "Panqueques tibios y suaves, helado de crema Cremolatti y una capa fina de azúcar caramelizada.", price: "$8.000", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Jean_Philippe_-_Dulce_de_Leche_Crepe.jpg/960px-Jean_Philippe_-_Dulce_de_Leche_Crepe.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
    ],
  },
];

export const getMenuCategoryById = (categoryId: string) => menuCategories.find((category) => category.id === categoryId) ?? null;
